import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { Providers as ThemeProvider } from "@/providers/ThemeProvider"
import { Providers as ReactQueryProvider } from "@/providers/ReactQueryProvider"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
